import { useState } from "react";
import { FileText, Download } from "lucide-react";
import { PageHeader } from "../shared/PageHeader";

const reports = [["Q2 2025 Risk Review", "Executive brief", "Jun 30, 2025", "Ready"], ["Apex Logistics Investigation", "Investigation report", "Jun 28, 2025", "Ready"], ["Vendor Concentration Analysis", "Analytics report", "Jun 24, 2025", "Draft"]];

export function ReportsPage() {
  const [selected, setSelected] = useState(0);
  const exportReport = () => { const blob = new Blob(["Q2 2025 Risk Review\n\nAt-risk exposure decreased 8.2% this quarter."], { type: "text/plain" }); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = "helios-q2-risk-review.txt"; link.click(); URL.revokeObjectURL(url); };
  return <><PageHeader eyebrow="Evidence and decisions" title="Reports" description="Review investigation findings and share CFO-ready summaries." action="Generate report" actionTo="/reports" /><div className="report-layout"><section className="feature-panel"><div className="panel-heading"><div><h2>Recent reports</h2><p>Generated for your workspace</p></div></div><div className="report-list">{reports.map(([title, type, date, status], index) => <button onClick={() => setSelected(index)} className={`report-row ${selected === index ? "selected" : ""}`} key={title}><FileText size={18} /><div><strong>{title}</strong><small>{type} · {date}</small></div><span className={`status status-${status.toLowerCase()}`}>{status}</span></button>)}</div></section><section className="feature-panel report-preview"><div className="preview-top"><span className="cfo-badge">Executive brief</span><button className="secondary-action" onClick={exportReport}><Download size={14} /> Export</button></div><p className="eyebrow">{reports[selected][0]}</p><h2>Financial risk remains concentrated in three vendors</h2><p className="preview-copy">At-risk exposure decreased 8.2% this quarter, while recoveries reached $486K. Two active investigations require executive review before the next payment run.</p><div className="preview-metrics"><div><strong>$2.84M</strong><span>At-risk exposure</span></div><div><strong>24</strong><span>Open investigations</span></div><div><strong>94%</strong><span>AI confidence</span></div></div></section></div></>;
}
